[tool.black]
line-length = 99
target-version = ['py38']

[tool.isort]
profile = "black"
known_typing = ["typing", "numpy.typing"]
known_sklearn = ["sklearn"]
sections = ["FUTURE", "TYPING", "STDLIB", "THIRDPARTY", "SKLEARN", "FIRSTPARTY", "LOCALFOLDER"]
